package uytubeLogica.publicar;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-11-14T13:58:41.829-03:00
 * Generated source version: 3.2.6
 *
 */
@WebService(targetNamespace = "http://publicar.uytubeLogica/", name = "WebServices")
@XmlSeeAlso({ObjectFactory.class, net.java.dev.jaxb.array.ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface WebServices {

    @WebMethod
    @Action(input = "http://publicar.uytubeLogica/WebServices/cambiarPrivLDRRequest", output = "http://publicar.uytubeLogica/WebServices/cambiarPrivLDRResponse")
    public void cambiarPrivLDR(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0,
        @WebParam(partName = "arg1", name = "arg1")
        java.lang.String arg1,
        @WebParam(partName = "arg2", name = "arg2")
        Privacidad arg2
    );

    @WebMethod
    @Action(input = "http://publicar.uytubeLogica/WebServices/operacionPruebaRequest", output = "http://publicar.uytubeLogica/WebServices/operacionPruebaResponse")
    public void operacionPrueba();

    @WebMethod
    @Action(input = "http://publicar.uytubeLogica/WebServices/listarLDRPublicasPorNombreRequest", output = "http://publicar.uytubeLogica/WebServices/listarLDRPublicasPorNombreResponse")
    @WebResult(name = "return", targetNamespace = "http://publicar.uytubeLogica/", partName = "return")
    public DtListaReproduccionArray listarLDRPublicasPorNombre(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://publicar.uytubeLogica/WebServices/listarLDRPorCategoriaRequest", output = "http://publicar.uytubeLogica/WebServices/listarLDRPorCategoriaResponse")
    @WebResult(name = "return", targetNamespace = "http://publicar.uytubeLogica/", partName = "return")
    public DtListaReproduccionArray listarLDRPorCategoria(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0,
        @WebParam(partName = "arg1", name = "arg1")
        Privacidad arg1,
        @WebParam(partName = "arg2", name = "arg2")
        java.lang.String arg2
    );

    @WebMethod
    @Action(input = "http://publicar.uytubeLogica/WebServices/verificarDispUsuarioRequest", output = "http://publicar.uytubeLogica/WebServices/verificarDispUsuarioResponse")
    @WebResult(name = "return", targetNamespace = "http://publicar.uytubeLogica/", partName = "return")
    public boolean verificarDispUsuario(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0,
        @WebParam(partName = "arg1", name = "arg1")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://publicar.uytubeLogica/WebServices/listarUsuariosQueSigueRequest", output = "http://publicar.uytubeLogica/WebServices/listarUsuariosQueSigueResponse")
    @WebResult(name = "return", targetNamespace = "http://publicar.uytubeLogica/", partName = "return")
    public net.java.dev.jaxb.array.StringArray listarUsuariosQueSigue(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://publicar.uytubeLogica/WebServices/listarCanalesPublicosPorNombreRequest", output = "http://publicar.uytubeLogica/WebServices/listarCanalesPublicosPorNombreResponse")
    @WebResult(name = "return", targetNamespace = "http://publicar.uytubeLogica/", partName = "return")
    public DtCanalArray listarCanalesPublicosPorNombre(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://publicar.uytubeLogica/WebServices/listarDatosUsuarioRequest", output = "http://publicar.uytubeLogica/WebServices/listarDatosUsuarioResponse")
    @WebResult(name = "return", targetNamespace = "http://publicar.uytubeLogica/", partName = "return")
    public DtUsuario listarDatosUsuario(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://publicar.uytubeLogica/WebServices/seguirUsuarioRequest", output = "http://publicar.uytubeLogica/WebServices/seguirUsuarioResponse")
    public void seguirUsuario(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0,
        @WebParam(partName = "arg1", name = "arg1")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://publicar.uytubeLogica/WebServices/valorarVideoRequest", output = "http://publicar.uytubeLogica/WebServices/valorarVideoResponse")
    public void valorarVideo(
        @WebParam(partName = "arg0", name = "arg0")
        int arg0,
        @WebParam(partName = "arg1", name = "arg1")
        java.lang.String arg1,
        @WebParam(partName = "arg2", name = "arg2")
        boolean arg2
    );

    @WebMethod
    @Action(input = "http://publicar.uytubeLogica/WebServices/infoLDRdeUsuarioRequest", output = "http://publicar.uytubeLogica/WebServices/infoLDRdeUsuarioResponse")
    @WebResult(name = "return", targetNamespace = "http://publicar.uytubeLogica/", partName = "return")
    public DtListaReproduccionArray infoLDRdeUsuario(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0,
        @WebParam(partName = "arg1", name = "arg1")
        java.lang.String arg1,
        @WebParam(partName = "arg2", name = "arg2")
        Privacidad arg2
    );

    @WebMethod
    @Action(input = "http://publicar.uytubeLogica/WebServices/mostrarInfoCanalRequest", output = "http://publicar.uytubeLogica/WebServices/mostrarInfoCanalResponse")
    @WebResult(name = "return", targetNamespace = "http://publicar.uytubeLogica/", partName = "return")
    public DtCanal mostrarInfoCanal(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://publicar.uytubeLogica/WebServices/agregarVideoListaRequest", output = "http://publicar.uytubeLogica/WebServices/agregarVideoListaResponse")
    public void agregarVideoLista(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0,
        @WebParam(partName = "arg1", name = "arg1")
        int arg1,
        @WebParam(partName = "arg2", name = "arg2")
        java.lang.String arg2
    );

    @WebMethod
    @Action(input = "http://publicar.uytubeLogica/WebServices/verDetallesVideoExtRequest", output = "http://publicar.uytubeLogica/WebServices/verDetallesVideoExtResponse")
    @WebResult(name = "return", targetNamespace = "http://publicar.uytubeLogica/", partName = "return")
    public DtInfoVideo verDetallesVideoExt(
        @WebParam(partName = "arg0", name = "arg0")
        int arg0
    );

    @WebMethod
    @Action(input = "http://publicar.uytubeLogica/WebServices/responderComentarioRequest", output = "http://publicar.uytubeLogica/WebServices/responderComentarioResponse")
    public void responderComentario(
        @WebParam(partName = "arg0", name = "arg0")
        int arg0,
        @WebParam(partName = "arg1", name = "arg1")
        int arg1,
        @WebParam(partName = "arg2", name = "arg2")
        java.lang.String arg2,
        @WebParam(partName = "arg3", name = "arg3")
        DtFecha arg3,
        @WebParam(partName = "arg4", name = "arg4")
        java.lang.String arg4
    );

    @WebMethod
    @Action(input = "http://publicar.uytubeLogica/WebServices/memberVideoRequest", output = "http://publicar.uytubeLogica/WebServices/memberVideoResponse")
    @WebResult(name = "return", targetNamespace = "http://publicar.uytubeLogica/", partName = "return")
    public boolean memberVideo(
        @WebParam(partName = "arg0", name = "arg0")
        int arg0
    );

	@WebMethod
    @Action(input = "http://publicar.uytubeLogica/WebServices/agregarVisitaRequest", output = "http://publicar.uytubeLogica/WebServices/agregarVisitaResponse")
    public void agregarVisita(
        @WebParam(partName = "arg0", name = "arg0")
        int arg0,
        @WebParam(partName = "arg1", name = "arg1")
        java.lang.String arg1
    );

	@WebMethod
    @Action(input = "http://publicar.uytubeLogica/WebServices/listarVideosPorCategoriaRequest", output = "http://publicar.uytubeLogica/WebServices/listarVideosPorCategoriaResponse")
    @WebResult(name = "return", targetNamespace = "http://publicar.uytubeLogica/", partName = "return")
    public DtVideoArray listarVideosPorCategoria(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0,
        @WebParam(partName = "arg1", name = "arg1")
        Privacidad arg1,
        @WebParam(partName = "arg2", name = "arg2")
        java.lang.String arg2
    );

    @WebMethod
    @Action(input = "http://publicar.uytubeLogica/WebServices/nuevoUsuarioRequest", output = "http://publicar.uytubeLogica/WebServices/nuevoUsuarioResponse")
    public void nuevoUsuario(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0,
        @WebParam(partName = "arg1", name = "arg1")
        java.lang.String arg1,
        @WebParam(partName = "arg2", name = "arg2")
        java.lang.String arg2,
        @WebParam(partName = "arg3", name = "arg3")
        java.lang.String arg3,
        @WebParam(partName = "arg4", name = "arg4")
        java.lang.String arg4,
        @WebParam(partName = "arg5", name = "arg5")
        DtFecha arg5,
        @WebParam(partName = "arg6", name = "arg6")
        byte[] arg6,
        @WebParam(partName = "arg7", name = "arg7")
        java.lang.String arg7,
        @WebParam(partName = "arg8", name = "arg8")
        java.lang.String arg8,
        @WebParam(partName = "arg9", name = "arg9")
        Privacidad arg9,
        @WebParam(partName = "arg10", name = "arg10")
        java.lang.String arg10
    );

    @WebMethod
    @Action(input = "http://publicar.uytubeLogica/WebServices/verificarLoginRequest", output = "http://publicar.uytubeLogica/WebServices/verificarLoginResponse")
    @WebResult(name = "return", targetNamespace = "http://publicar.uytubeLogica/", partName = "return")
    public boolean verificarLogin(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0,
        @WebParam(partName = "arg1", name = "arg1")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://publicar.uytubeLogica/WebServices/nuevaListaParticularRequest", output = "http://publicar.uytubeLogica/WebServices/nuevaListaParticularResponse")
    public void nuevaListaParticular(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0,
        @WebParam(partName = "arg1", name = "arg1")
        java.lang.String arg1,
        @WebParam(partName = "arg2", name = "arg2")
        Privacidad arg2
    );

    @WebMethod
    @Action(input = "http://publicar.uytubeLogica/WebServices/nuevoComentarioRequest", output = "http://publicar.uytubeLogica/WebServices/nuevoComentarioResponse")
    public void nuevoComentario(
        @WebParam(partName = "arg0", name = "arg0")
        int arg0,
        @WebParam(partName = "arg1", name = "arg1")
        java.lang.String arg1,
        @WebParam(partName = "arg2", name = "arg2")
        DtFecha arg2,
        @WebParam(partName = "arg3", name = "arg3")
        java.lang.String arg3
    );

    @WebMethod
    @Action(input = "http://publicar.uytubeLogica/WebServices/eliminarVideoListaRequest", output = "http://publicar.uytubeLogica/WebServices/eliminarVideoListaResponse")
    public void eliminarVideoLista(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0,
        @WebParam(partName = "arg1", name = "arg1")
        int arg1,
        @WebParam(partName = "arg2", name = "arg2")
        java.lang.String arg2
    );

    @WebMethod
    @Action(input = "http://publicar.uytubeLogica/WebServices/listarVideoListaReproduccionRequest", output = "http://publicar.uytubeLogica/WebServices/listarVideoListaReproduccionResponse")
    @WebResult(name = "return", targetNamespace = "http://publicar.uytubeLogica/", partName = "return")
    public DtVideoArray listarVideoListaReproduccion(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0,
        @WebParam(partName = "arg1", name = "arg1")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://publicar.uytubeLogica/WebServices/getEstadoValoracionRequest", output = "http://publicar.uytubeLogica/WebServices/getEstadoValoracionResponse")
    @WebResult(name = "return", targetNamespace = "http://publicar.uytubeLogica/", partName = "return")
    public java.lang.String getEstadoValoracion(
        @WebParam(partName = "arg0", name = "arg0")
        int arg0,
        @WebParam(partName = "arg1", name = "arg1")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://publicar.uytubeLogica/WebServices/listarCategoriasRequest", output = "http://publicar.uytubeLogica/WebServices/listarCategoriasResponse")
    @WebResult(name = "return", targetNamespace = "http://publicar.uytubeLogica/", partName = "return")
    public DtCategoriaArray listarCategorias();

    @WebMethod
    @Action(input = "http://publicar.uytubeLogica/WebServices/listarVideoHistorialRequest", output = "http://publicar.uytubeLogica/WebServices/listarVideoHistorialResponse")
    @WebResult(name = "return", targetNamespace = "http://publicar.uytubeLogica/", partName = "return")
    public DtVideoHistorialArray listarVideoHistorial(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    );

	@WebMethod
    @Action(input = "http://publicar.uytubeLogica/WebServices/memberListaReproduccionPropiaRequest", output = "http://publicar.uytubeLogica/WebServices/memberListaReproduccionPropiaResponse")
    @WebResult(name = "return", targetNamespace = "http://publicar.uytubeLogica/", partName = "return")
    public boolean memberListaReproduccionPropia(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0,
        @WebParam(partName = "arg1", name = "arg1")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://publicar.uytubeLogica/WebServices/listarComentariosRequest", output = "http://publicar.uytubeLogica/WebServices/listarComentariosResponse")
    @WebResult(name = "return", targetNamespace = "http://publicar.uytubeLogica/", partName = "return")
    public DtComentarioArray listarComentarios(
        @WebParam(partName = "arg0", name = "arg0")
        int arg0
    );

    @WebMethod
    @Action(input = "http://publicar.uytubeLogica/WebServices/obtenerDtsVideosListaReproduccionUsuarioRequest", output = "http://publicar.uytubeLogica/WebServices/obtenerDtsVideosListaReproduccionUsuarioResponse")
    @WebResult(name = "return", targetNamespace = "http://publicar.uytubeLogica/", partName = "return")
    public DtVideoArray obtenerDtsVideosListaReproduccionUsuario(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0,
        @WebParam(partName = "arg1", name = "arg1")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://publicar.uytubeLogica/WebServices/infoListaReproduccionRequest", output = "http://publicar.uytubeLogica/WebServices/infoListaReproduccionResponse")
    @WebResult(name = "return", targetNamespace = "http://publicar.uytubeLogica/", partName = "return")
    public DtListaReproduccion infoListaReproduccion(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0,
        @WebParam(partName = "arg1", name = "arg1")
        java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://publicar.uytubeLogica/WebServices/aniadirVideoRequest", output = "http://publicar.uytubeLogica/WebServices/aniadirVideoResponse")
    public void aniadirVideo(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0,
        @WebParam(partName = "arg1", name = "arg1")
        java.lang.String arg1,
        @WebParam(partName = "arg2", name = "arg2")
        java.lang.String arg2,
        @WebParam(partName = "arg3", name = "arg3")
        int arg3,
        @WebParam(partName = "arg4", name = "arg4")
        DtFecha arg4,
        @WebParam(partName = "arg5", name = "arg5")
        java.lang.String arg5,
        @WebParam(partName = "arg6", name = "arg6")
        DtCategoria arg6,
        @WebParam(partName = "arg7", name = "arg7")
        Privacidad arg7
    );

    @WebMethod
    @Action(input = "http://publicar.uytubeLogica/WebServices/listarUsuariosQueLeSigueRequest", output = "http://publicar.uytubeLogica/WebServices/listarUsuariosQueLeSigueResponse")
    @WebResult(name = "return", targetNamespace = "http://publicar.uytubeLogica/", partName = "return")
    public net.java.dev.jaxb.array.StringArray listarUsuariosQueLeSigue(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://publicar.uytubeLogica/WebServices/infoVideosCanalRequest", output = "http://publicar.uytubeLogica/WebServices/infoVideosCanalResponse")
    @WebResult(name = "return", targetNamespace = "http://publicar.uytubeLogica/", partName = "return")
    public DtVideoArray infoVideosCanal(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0,
        @WebParam(partName = "arg1", name = "arg1")
        java.lang.String arg1,
        @WebParam(partName = "arg2", name = "arg2")
        Privacidad arg2
    );

    @WebMethod
    @Action(input = "http://publicar.uytubeLogica/WebServices/listarLDRdeUsuarioRequest", output = "http://publicar.uytubeLogica/WebServices/listarLDRdeUsuarioResponse")
    @WebResult(name = "return", targetNamespace = "http://publicar.uytubeLogica/", partName = "return")
    public net.java.dev.jaxb.array.StringArray listarLDRdeUsuario(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://publicar.uytubeLogica/WebServices/bajaUsuarioRequest", output = "http://publicar.uytubeLogica/WebServices/bajaUsuarioResponse")
    public void bajaUsuario(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    );

	@WebMethod
    @Action(input = "http://publicar.uytubeLogica/WebServices/infoAddVideoRequest", output = "http://publicar.uytubeLogica/WebServices/infoAddVideoResponse")
    @WebResult(name = "return", targetNamespace = "http://publicar.uytubeLogica/", partName = "return")
    public DtVideo infoAddVideo(
        @WebParam(partName = "arg0", name = "arg0")
        int arg0
    );

    @WebMethod
    @Action(input = "http://publicar.uytubeLogica/WebServices/cargarDatosRequest", output = "http://publicar.uytubeLogica/WebServices/cargarDatosResponse")
    public void cargarDatos();

    @WebMethod
    @Action(input = "http://publicar.uytubeLogica/WebServices/listarVideosPublicosPorNombreRequest", output = "http://publicar.uytubeLogica/WebServices/listarVideosPublicosPorNombreResponse")
    @WebResult(name = "return", targetNamespace = "http://publicar.uytubeLogica/", partName = "return")
    public DtVideoArray listarVideosPublicosPorNombre(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    );

    @WebMethod
    @Action(input = "http://publicar.uytubeLogica/WebServices/dejarUsuarioRequest", output = "http://publicar.uytubeLogica/WebServices/dejarUsuarioResponse")
    public void dejarUsuario(
        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0,
        @WebParam(partName = "arg1", name = "arg1")
        java.lang.String arg1
    );
}
