
package uytubeLogica.publicar;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-11-14T13:58:41.679-03:00
 * Generated source version: 3.2.6
 *
 */
public final class WebServices_WebServicesPort_Client {

    private static final QName SERVICE_NAME = new QName("http://publicar.uytubeLogica/", "WebServicesService");

    private WebServices_WebServicesPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WebServicesService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        WebServicesService ss = new WebServicesService(wsdlURL, SERVICE_NAME);
        WebServices port = ss.getWebServicesPort();

        {
        System.out.println("Invoking cambiarPrivLDR...");
        java.lang.String _cambiarPrivLDR_arg0 = "_cambiarPrivLDR_arg0-1072235729";
        java.lang.String _cambiarPrivLDR_arg1 = "_cambiarPrivLDR_arg11227159394";
        uytubeLogica.publicar.Privacidad _cambiarPrivLDR_arg2 = uytubeLogica.publicar.Privacidad.PRIVADO;
        port.cambiarPrivLDR(_cambiarPrivLDR_arg0, _cambiarPrivLDR_arg1, _cambiarPrivLDR_arg2);


        }
        {
        System.out.println("Invoking operacionPrueba...");
        port.operacionPrueba();


        }
        {
        System.out.println("Invoking listarLDRPublicasPorNombre...");
        java.lang.String _listarLDRPublicasPorNombre_arg0 = "_listarLDRPublicasPorNombre_arg0-643517274";
        uytubeLogica.publicar.DtListaReproduccionArray _listarLDRPublicasPorNombre__return = port.listarLDRPublicasPorNombre(_listarLDRPublicasPorNombre_arg0);
        System.out.println("listarLDRPublicasPorNombre.result=" + _listarLDRPublicasPorNombre__return);


        }
        {
        System.out.println("Invoking listarLDRPorCategoria...");
        java.lang.String _listarLDRPorCategoria_arg0 = "_listarLDRPorCategoria_arg0739741563";
        uytubeLogica.publicar.Privacidad _listarLDRPorCategoria_arg1 = uytubeLogica.publicar.Privacidad.PUBLICO;
        java.lang.String _listarLDRPorCategoria_arg2 = "_listarLDRPorCategoria_arg2-843542554";
        uytubeLogica.publicar.DtListaReproduccionArray _listarLDRPorCategoria__return = port.listarLDRPorCategoria(_listarLDRPorCategoria_arg0, _listarLDRPorCategoria_arg1, _listarLDRPorCategoria_arg2);
        System.out.println("listarLDRPorCategoria.result=" + _listarLDRPorCategoria__return);


        }
        {
        System.out.println("Invoking verificarDispUsuario...");
        java.lang.String _verificarDispUsuario_arg0 = "_verificarDispUsuario_arg0-492884628";
        java.lang.String _verificarDispUsuario_arg1 = "_verificarDispUsuario_arg1490620539";
        boolean _verificarDispUsuario__return = port.verificarDispUsuario(_verificarDispUsuario_arg0, _verificarDispUsuario_arg1);
        System.out.println("verificarDispUsuario.result=" + _verificarDispUsuario__return);


        }
        {
        System.out.println("Invoking listarUsuariosQueSigue...");
        java.lang.String _listarUsuariosQueSigue_arg0 = "_listarUsuariosQueSigue_arg01819410053";
        net.java.dev.jaxb.array.StringArray _listarUsuariosQueSigue__return = port.listarUsuariosQueSigue(_listarUsuariosQueSigue_arg0);
        System.out.println("listarUsuariosQueSigue.result=" + _listarUsuariosQueSigue__return);


        }
        {
        System.out.println("Invoking listarCanalesPublicosPorNombre...");
        java.lang.String _listarCanalesPublicosPorNombre_arg0 = "_listarCanalesPublicosPorNombre_arg0190104812";
        uytubeLogica.publicar.DtCanalArray _listarCanalesPublicosPorNombre__return = port.listarCanalesPublicosPorNombre(_listarCanalesPublicosPorNombre_arg0);
        System.out.println("listarCanalesPublicosPorNombre.result=" + _listarCanalesPublicosPorNombre__return);


        }
        {
        System.out.println("Invoking listarDatosUsuario...");
        java.lang.String _listarDatosUsuario_arg0 = "_listarDatosUsuario_arg0-1375768773";
        uytubeLogica.publicar.DtUsuario _listarDatosUsuario__return = port.listarDatosUsuario(_listarDatosUsuario_arg0);
        System.out.println("listarDatosUsuario.result=" + _listarDatosUsuario__return);


        }
        {
        System.out.println("Invoking seguirUsuario...");
        java.lang.String _seguirUsuario_arg0 = "_seguirUsuario_arg01443210613";
        java.lang.String _seguirUsuario_arg1 = "_seguirUsuario_arg1-274162441";
        port.seguirUsuario(_seguirUsuario_arg0, _seguirUsuario_arg1);


        }
        {
        System.out.println("Invoking valorarVideo...");
        int _valorarVideo_arg0 = 1419933030;
        java.lang.String _valorarVideo_arg1 = "_valorarVideo_arg1-406794180";
        boolean _valorarVideo_arg2 = true;
        port.valorarVideo(_valorarVideo_arg0, _valorarVideo_arg1, _valorarVideo_arg2);


        }
        {
        System.out.println("Invoking infoLDRdeUsuario...");
        java.lang.String _infoLDRdeUsuario_arg0 = "_infoLDRdeUsuario_arg01750182343";
        java.lang.String _infoLDRdeUsuario_arg1 = "_infoLDRdeUsuario_arg1242894855";
        uytubeLogica.publicar.Privacidad _infoLDRdeUsuario_arg2 = uytubeLogica.publicar.Privacidad.PUBLICO;
        uytubeLogica.publicar.DtListaReproduccionArray _infoLDRdeUsuario__return = port.infoLDRdeUsuario(_infoLDRdeUsuario_arg0, _infoLDRdeUsuario_arg1, _infoLDRdeUsuario_arg2);
        System.out.println("infoLDRdeUsuario.result=" + _infoLDRdeUsuario__return);


        }
        {
        System.out.println("Invoking mostrarInfoCanal...");
        java.lang.String _mostrarInfoCanal_arg0 = "_mostrarInfoCanal_arg0-1918009144";
        uytubeLogica.publicar.DtCanal _mostrarInfoCanal__return = port.mostrarInfoCanal(_mostrarInfoCanal_arg0);
        System.out.println("mostrarInfoCanal.result=" + _mostrarInfoCanal__return);


        }
        {
        System.out.println("Invoking agregarVideoLista...");
        java.lang.String _agregarVideoLista_arg0 = "_agregarVideoLista_arg0-1975270910";
        int _agregarVideoLista_arg1 = -921359534;
        java.lang.String _agregarVideoLista_arg2 = "_agregarVideoLista_arg22015835635";
        port.agregarVideoLista(_agregarVideoLista_arg0, _agregarVideoLista_arg1, _agregarVideoLista_arg2);


        }
        {
        System.out.println("Invoking verDetallesVideoExt...");
        int _verDetallesVideoExt_arg0 = -543994059;
        uytubeLogica.publicar.DtInfoVideo _verDetallesVideoExt__return = port.verDetallesVideoExt(_verDetallesVideoExt_arg0);
        System.out.println("verDetallesVideoExt.result=" + _verDetallesVideoExt__return);


        }
        {
        System.out.println("Invoking responderComentario...");
        int _responderComentario_arg0 = 77276956;
        int _responderComentario_arg1 = -1181704681;
        java.lang.String _responderComentario_arg2 = "_responderComentario_arg2-191789415";
        uytubeLogica.publicar.DtFecha _responderComentario_arg3 = new uytubeLogica.publicar.DtFecha();
        _responderComentario_arg3.setFecha(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-10-28T15:58:54.617-03:00"));
        java.lang.String _responderComentario_arg4 = "_responderComentario_arg4200268746";
        port.responderComentario(_responderComentario_arg0, _responderComentario_arg1, _responderComentario_arg2, _responderComentario_arg3, _responderComentario_arg4);


        }
        {
        System.out.println("Invoking listarVideosPorCategoria...");
        java.lang.String _listarVideosPorCategoria_arg0 = "_listarVideosPorCategoria_arg0-51506105";
        uytubeLogica.publicar.Privacidad _listarVideosPorCategoria_arg1 = uytubeLogica.publicar.Privacidad.PUBLICO;
        java.lang.String _listarVideosPorCategoria_arg2 = "_listarVideosPorCategoria_arg2-1235399179";
        uytubeLogica.publicar.DtVideoArray _listarVideosPorCategoria__return = port.listarVideosPorCategoria(_listarVideosPorCategoria_arg0, _listarVideosPorCategoria_arg1, _listarVideosPorCategoria_arg2);
        System.out.println("listarVideosPorCategoria.result=" + _listarVideosPorCategoria__return);


        }
        {
        System.out.println("Invoking nuevoUsuario...");
        java.lang.String _nuevoUsuario_arg0 = "_nuevoUsuario_arg055103854";
        java.lang.String _nuevoUsuario_arg1 = "_nuevoUsuario_arg11608553735";
        java.lang.String _nuevoUsuario_arg2 = "_nuevoUsuario_arg22083148738";
        java.lang.String _nuevoUsuario_arg3 = "_nuevoUsuario_arg3-1968314167";
        java.lang.String _nuevoUsuario_arg4 = "_nuevoUsuario_arg4634575223";
        uytubeLogica.publicar.DtFecha _nuevoUsuario_arg5 = new uytubeLogica.publicar.DtFecha();
        _nuevoUsuario_arg5.setFecha(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-10-28T15:58:54.620-03:00"));
        byte[] _nuevoUsuario_arg6 = new byte[] {};
        java.lang.String _nuevoUsuario_arg7 = "_nuevoUsuario_arg7-989417210";
        java.lang.String _nuevoUsuario_arg8 = "_nuevoUsuario_arg8847414784";
        uytubeLogica.publicar.Privacidad _nuevoUsuario_arg9 = uytubeLogica.publicar.Privacidad.PRIVADO;
        java.lang.String _nuevoUsuario_arg10 = "_nuevoUsuario_arg10-969873261";
        port.nuevoUsuario(_nuevoUsuario_arg0, _nuevoUsuario_arg1, _nuevoUsuario_arg2, _nuevoUsuario_arg3, _nuevoUsuario_arg4, _nuevoUsuario_arg5, _nuevoUsuario_arg6, _nuevoUsuario_arg7, _nuevoUsuario_arg8, _nuevoUsuario_arg9, _nuevoUsuario_arg10);


        }
        {
        System.out.println("Invoking verificarLogin...");
        java.lang.String _verificarLogin_arg0 = "_verificarLogin_arg0-1818427100";
        java.lang.String _verificarLogin_arg1 = "_verificarLogin_arg1-1606174415";
        boolean _verificarLogin__return = port.verificarLogin(_verificarLogin_arg0, _verificarLogin_arg1);
        System.out.println("verificarLogin.result=" + _verificarLogin__return);


        }
        {
        System.out.println("Invoking nuevaListaParticular...");
        java.lang.String _nuevaListaParticular_arg0 = "_nuevaListaParticular_arg078796782";
        java.lang.String _nuevaListaParticular_arg1 = "_nuevaListaParticular_arg1148960747";
        uytubeLogica.publicar.Privacidad _nuevaListaParticular_arg2 = uytubeLogica.publicar.Privacidad.PUBLICO;
        port.nuevaListaParticular(_nuevaListaParticular_arg0, _nuevaListaParticular_arg1, _nuevaListaParticular_arg2);


        }
        {
        System.out.println("Invoking nuevoComentario...");
        int _nuevoComentario_arg0 = 287137333;
        java.lang.String _nuevoComentario_arg1 = "_nuevoComentario_arg1327227570";
        uytubeLogica.publicar.DtFecha _nuevoComentario_arg2 = new uytubeLogica.publicar.DtFecha();
        _nuevoComentario_arg2.setFecha(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-10-28T15:58:54.622-03:00"));
        java.lang.String _nuevoComentario_arg3 = "_nuevoComentario_arg31218084997";
        port.nuevoComentario(_nuevoComentario_arg0, _nuevoComentario_arg1, _nuevoComentario_arg2, _nuevoComentario_arg3);


        }
        {
        System.out.println("Invoking eliminarVideoLista...");
        java.lang.String _eliminarVideoLista_arg0 = "_eliminarVideoLista_arg0-1212959072";
        int _eliminarVideoLista_arg1 = -2046931310;
        java.lang.String _eliminarVideoLista_arg2 = "_eliminarVideoLista_arg21432646140";
        port.eliminarVideoLista(_eliminarVideoLista_arg0, _eliminarVideoLista_arg1, _eliminarVideoLista_arg2);


        }
        {
        System.out.println("Invoking listarVideoListaReproduccion...");
        java.lang.String _listarVideoListaReproduccion_arg0 = "_listarVideoListaReproduccion_arg01027966697";
        java.lang.String _listarVideoListaReproduccion_arg1 = "_listarVideoListaReproduccion_arg1917926675";
        uytubeLogica.publicar.DtVideoArray _listarVideoListaReproduccion__return = port.listarVideoListaReproduccion(_listarVideoListaReproduccion_arg0, _listarVideoListaReproduccion_arg1);
        System.out.println("listarVideoListaReproduccion.result=" + _listarVideoListaReproduccion__return);


        }
        {
        System.out.println("Invoking getEstadoValoracion...");
        int _getEstadoValoracion_arg0 = -2087926085;
        java.lang.String _getEstadoValoracion_arg1 = "_getEstadoValoracion_arg1-1565630471";
        java.lang.String _getEstadoValoracion__return = port.getEstadoValoracion(_getEstadoValoracion_arg0, _getEstadoValoracion_arg1);
        System.out.println("getEstadoValoracion.result=" + _getEstadoValoracion__return);


        }
        {
        System.out.println("Invoking listarCategorias...");
        uytubeLogica.publicar.DtCategoriaArray _listarCategorias__return = port.listarCategorias();
        System.out.println("listarCategorias.result=" + _listarCategorias__return);


        }
        {
        System.out.println("Invoking memberListaReproduccionPropia...");
        java.lang.String _memberListaReproduccionPropia_arg0 = "_memberListaReproduccionPropia_arg074896647";
        java.lang.String _memberListaReproduccionPropia_arg1 = "_memberListaReproduccionPropia_arg11075502267";
        boolean _memberListaReproduccionPropia__return = port.memberListaReproduccionPropia(_memberListaReproduccionPropia_arg0, _memberListaReproduccionPropia_arg1);
        System.out.println("memberListaReproduccionPropia.result=" + _memberListaReproduccionPropia__return);


        }
        {
        System.out.println("Invoking listarComentarios...");
        int _listarComentarios_arg0 = -307412844;
        uytubeLogica.publicar.DtComentarioArray _listarComentarios__return = port.listarComentarios(_listarComentarios_arg0);
        System.out.println("listarComentarios.result=" + _listarComentarios__return);


        }
        {
        System.out.println("Invoking obtenerDtsVideosListaReproduccionUsuario...");
        java.lang.String _obtenerDtsVideosListaReproduccionUsuario_arg0 = "_obtenerDtsVideosListaReproduccionUsuario_arg0-2023825120";
        java.lang.String _obtenerDtsVideosListaReproduccionUsuario_arg1 = "_obtenerDtsVideosListaReproduccionUsuario_arg1835243095";
        uytubeLogica.publicar.DtVideoArray _obtenerDtsVideosListaReproduccionUsuario__return = port.obtenerDtsVideosListaReproduccionUsuario(_obtenerDtsVideosListaReproduccionUsuario_arg0, _obtenerDtsVideosListaReproduccionUsuario_arg1);
        System.out.println("obtenerDtsVideosListaReproduccionUsuario.result=" + _obtenerDtsVideosListaReproduccionUsuario__return);


        }
        {
        System.out.println("Invoking infoListaReproduccion...");
        java.lang.String _infoListaReproduccion_arg0 = "_infoListaReproduccion_arg0-48989563";
        java.lang.String _infoListaReproduccion_arg1 = "_infoListaReproduccion_arg1-1858211275";
        uytubeLogica.publicar.DtListaReproduccion _infoListaReproduccion__return = port.infoListaReproduccion(_infoListaReproduccion_arg0, _infoListaReproduccion_arg1);
        System.out.println("infoListaReproduccion.result=" + _infoListaReproduccion__return);


        }
        {
        System.out.println("Invoking aniadirVideo...");
        java.lang.String _aniadirVideo_arg0 = "_aniadirVideo_arg0814548902";
        java.lang.String _aniadirVideo_arg1 = "_aniadirVideo_arg1-113898942";
        java.lang.String _aniadirVideo_arg2 = "_aniadirVideo_arg21892377933";
        int _aniadirVideo_arg3 = -1018891026;
        uytubeLogica.publicar.DtFecha _aniadirVideo_arg4 = new uytubeLogica.publicar.DtFecha();
        _aniadirVideo_arg4.setFecha(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-10-28T15:58:54.625-03:00"));
        java.lang.String _aniadirVideo_arg5 = "_aniadirVideo_arg5432746039";
        uytubeLogica.publicar.DtCategoria _aniadirVideo_arg6 = new uytubeLogica.publicar.DtCategoria();
        _aniadirVideo_arg6.setNombre("Nombre-1207070528");
        uytubeLogica.publicar.Privacidad _aniadirVideo_arg7 = uytubeLogica.publicar.Privacidad.PUBLICO;
        port.aniadirVideo(_aniadirVideo_arg0, _aniadirVideo_arg1, _aniadirVideo_arg2, _aniadirVideo_arg3, _aniadirVideo_arg4, _aniadirVideo_arg5, _aniadirVideo_arg6, _aniadirVideo_arg7);


        }
        {
        System.out.println("Invoking listarUsuariosQueLeSigue...");
        java.lang.String _listarUsuariosQueLeSigue_arg0 = "_listarUsuariosQueLeSigue_arg0-1540663158";
        net.java.dev.jaxb.array.StringArray _listarUsuariosQueLeSigue__return = port.listarUsuariosQueLeSigue(_listarUsuariosQueLeSigue_arg0);
        System.out.println("listarUsuariosQueLeSigue.result=" + _listarUsuariosQueLeSigue__return);


        }
        {
        System.out.println("Invoking infoVideosCanal...");
        java.lang.String _infoVideosCanal_arg0 = "_infoVideosCanal_arg02068661218";
        java.lang.String _infoVideosCanal_arg1 = "_infoVideosCanal_arg1-529640127";
        uytubeLogica.publicar.Privacidad _infoVideosCanal_arg2 = uytubeLogica.publicar.Privacidad.PRIVADO;
        uytubeLogica.publicar.DtVideoArray _infoVideosCanal__return = port.infoVideosCanal(_infoVideosCanal_arg0, _infoVideosCanal_arg1, _infoVideosCanal_arg2);
        System.out.println("infoVideosCanal.result=" + _infoVideosCanal__return);


        }
        {
        System.out.println("Invoking listarLDRdeUsuario...");
        java.lang.String _listarLDRdeUsuario_arg0 = "_listarLDRdeUsuario_arg01853859544";
        net.java.dev.jaxb.array.StringArray _listarLDRdeUsuario__return = port.listarLDRdeUsuario(_listarLDRdeUsuario_arg0);
        System.out.println("listarLDRdeUsuario.result=" + _listarLDRdeUsuario__return);


        }
        {
        System.out.println("Invoking infoAddVideo...");
        int _infoAddVideo_arg0 = 1251173204;
        uytubeLogica.publicar.DtVideo _infoAddVideo__return = port.infoAddVideo(_infoAddVideo_arg0);
        System.out.println("infoAddVideo.result=" + _infoAddVideo__return);


        }
        {
        System.out.println("Invoking cargarDatos...");
        port.cargarDatos();


        }
        {
        System.out.println("Invoking listarVideosPublicosPorNombre...");
        java.lang.String _listarVideosPublicosPorNombre_arg0 = "_listarVideosPublicosPorNombre_arg028465617";
        uytubeLogica.publicar.DtVideoArray _listarVideosPublicosPorNombre__return = port.listarVideosPublicosPorNombre(_listarVideosPublicosPorNombre_arg0);
        System.out.println("listarVideosPublicosPorNombre.result=" + _listarVideosPublicosPorNombre__return);


        }
        {
        System.out.println("Invoking dejarUsuario...");
        java.lang.String _dejarUsuario_arg0 = "_dejarUsuario_arg0610707597";
        java.lang.String _dejarUsuario_arg1 = "_dejarUsuario_arg1-681665690";
        port.dejarUsuario(_dejarUsuario_arg0, _dejarUsuario_arg1);


        }

        System.exit(0);
    }

}
