
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package uytubeLogica.publicar;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-11-14T13:58:41.786-03:00
 * Generated source version: 3.2.6
 *
 */

@javax.jws.WebService(
                      serviceName = "WebServicesService",
                      portName = "WebServicesPort",
                      targetNamespace = "http://publicar.uytubeLogica/",
                      wsdlLocation = "http://localhost:9128/webservices?wsdl",
                      endpointInterface = "uytubeLogica.publicar.WebServices")

public class WebServicesPortImpl implements WebServices {

    private static final Logger LOG = Logger.getLogger(WebServicesPortImpl.class.getName());

    /* (non-Javadoc)
     * @see uytubeLogica.publicar.WebServices#cambiarPrivLDR(java.lang.String arg0, java.lang.String arg1, uytubeLogica.publicar.Privacidad arg2)*
     */
    public void cambiarPrivLDR(java.lang.String arg0, java.lang.String arg1, Privacidad arg2) {
        LOG.info("Executing operation cambiarPrivLDR");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see uytubeLogica.publicar.WebServices#operacionPrueba()*
     */
    public void operacionPrueba() {
        LOG.info("Executing operation operacionPrueba");
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see uytubeLogica.publicar.WebServices#listarLDRPublicasPorNombre(java.lang.String arg0)*
     */
    public uytubeLogica.publicar.DtListaReproduccionArray listarLDRPublicasPorNombre(java.lang.String arg0) {
        LOG.info("Executing operation listarLDRPublicasPorNombre");
        System.out.println(arg0);
        try {
            uytubeLogica.publicar.DtListaReproduccionArray _return = new uytubeLogica.publicar.DtListaReproduccionArray();
            java.util.List<uytubeLogica.publicar.DtListaReproduccion> _returnItem = new java.util.ArrayList<uytubeLogica.publicar.DtListaReproduccion>();
            uytubeLogica.publicar.DtListaReproduccion _returnItemVal1 = new uytubeLogica.publicar.DtListaReproduccion();
            java.util.List<uytubeLogica.publicar.DtCategoria> _returnItemVal1CategoriasLDR = new java.util.ArrayList<uytubeLogica.publicar.DtCategoria>();
            _returnItemVal1.getCategoriasLDR().addAll(_returnItemVal1CategoriasLDR);
            _returnItemVal1.setNombre("Nombre-1127601848");
            uytubeLogica.publicar.Privacidad _returnItemVal1Privado = uytubeLogica.publicar.Privacidad.PRIVADO;
            _returnItemVal1.setPrivado(_returnItemVal1Privado);
            _returnItemVal1.setPropietario("Propietario-91283187");
            uytubeLogica.publicar.TipoLista _returnItemVal1TipoL = uytubeLogica.publicar.TipoLista.PORDEFECTO;
            _returnItemVal1.setTipoL(_returnItemVal1TipoL);
            _returnItemVal1.setUltimoVideo(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-10-28T15:58:54.702-03:00"));
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see uytubeLogica.publicar.WebServices#listarLDRPorCategoria(java.lang.String arg0, uytubeLogica.publicar.Privacidad arg1, java.lang.String arg2)*
     */
    public uytubeLogica.publicar.DtListaReproduccionArray listarLDRPorCategoria(java.lang.String arg0, Privacidad arg1, java.lang.String arg2) {
        LOG.info("Executing operation listarLDRPorCategoria");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        try {
            uytubeLogica.publicar.DtListaReproduccionArray _return = new uytubeLogica.publicar.DtListaReproduccionArray();
            java.util.List<uytubeLogica.publicar.DtListaReproduccion> _returnItem = new java.util.ArrayList<uytubeLogica.publicar.DtListaReproduccion>();
            uytubeLogica.publicar.DtListaReproduccion _returnItemVal1 = new uytubeLogica.publicar.DtListaReproduccion();
            java.util.List<uytubeLogica.publicar.DtCategoria> _returnItemVal1CategoriasLDR = new java.util.ArrayList<uytubeLogica.publicar.DtCategoria>();
            _returnItemVal1.getCategoriasLDR().addAll(_returnItemVal1CategoriasLDR);
            _returnItemVal1.setNombre("Nombre1999994430");
            uytubeLogica.publicar.Privacidad _returnItemVal1Privado = uytubeLogica.publicar.Privacidad.PRIVADO;
            _returnItemVal1.setPrivado(_returnItemVal1Privado);
            _returnItemVal1.setPropietario("Propietario97289151");
            uytubeLogica.publicar.TipoLista _returnItemVal1TipoL = uytubeLogica.publicar.TipoLista.PORDEFECTO;
            _returnItemVal1.setTipoL(_returnItemVal1TipoL);
            _returnItemVal1.setUltimoVideo(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-10-28T15:58:54.703-03:00"));
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see uytubeLogica.publicar.WebServices#verificarDispUsuario(java.lang.String arg0, java.lang.String arg1)*
     */
    public boolean verificarDispUsuario(java.lang.String arg0, java.lang.String arg1) {
        LOG.info("Executing operation verificarDispUsuario");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            boolean _return = true;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see uytubeLogica.publicar.WebServices#listarUsuariosQueSigue(java.lang.String arg0)*
     */
    public net.java.dev.jaxb.array.StringArray listarUsuariosQueSigue(java.lang.String arg0) {
        LOG.info("Executing operation listarUsuariosQueSigue");
        System.out.println(arg0);
        try {
            net.java.dev.jaxb.array.StringArray _return = new net.java.dev.jaxb.array.StringArray();
            java.util.List<java.lang.String> _returnItem = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnItemVal1 = "_returnItemVal-450480077";
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see uytubeLogica.publicar.WebServices#listarCanalesPublicosPorNombre(java.lang.String arg0)*
     */
    public uytubeLogica.publicar.DtCanalArray listarCanalesPublicosPorNombre(java.lang.String arg0) {
        LOG.info("Executing operation listarCanalesPublicosPorNombre");
        System.out.println(arg0);
        try {
            uytubeLogica.publicar.DtCanalArray _return = new uytubeLogica.publicar.DtCanalArray();
            java.util.List<uytubeLogica.publicar.DtCanal> _returnItem = new java.util.ArrayList<uytubeLogica.publicar.DtCanal>();
            uytubeLogica.publicar.DtCanal _returnItemVal1 = new uytubeLogica.publicar.DtCanal();
            uytubeLogica.publicar.DtCategoria _returnItemVal1Categoria = new uytubeLogica.publicar.DtCategoria();
            _returnItemVal1Categoria.setNombre("Nombre44298059");
            _returnItemVal1.setCategoria(_returnItemVal1Categoria);
            _returnItemVal1.setDescripcion("Descripcion-834455850");
            _returnItemVal1.setNombre("Nombre-123555089");
            uytubeLogica.publicar.Privacidad _returnItemVal1Privado = uytubeLogica.publicar.Privacidad.PUBLICO;
            _returnItemVal1.setPrivado(_returnItemVal1Privado);
            _returnItemVal1.setPropietario("Propietario363371352");
            _returnItemVal1.setUltimoVideo(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-10-28T15:58:54.704-03:00"));
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see uytubeLogica.publicar.WebServices#listarDatosUsuario(java.lang.String arg0)*
     */
    public uytubeLogica.publicar.DtUsuario listarDatosUsuario(java.lang.String arg0) {
        LOG.info("Executing operation listarDatosUsuario");
        System.out.println(arg0);
        try {
            uytubeLogica.publicar.DtUsuario _return = new uytubeLogica.publicar.DtUsuario();
            _return.setApellido("Apellido-1751197390");
            _return.setEmail("Email954602316");
            uytubeLogica.publicar.DtFecha _returnFechaNacimiento = new uytubeLogica.publicar.DtFecha();
            _returnFechaNacimiento.setFecha(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-10-28T15:58:54.705-03:00"));
            _return.setFechaNacimiento(_returnFechaNacimiento);
            byte[] _returnFoto = new byte[] {};
            _return.setFoto(_returnFoto);
            _return.setNickname("Nickname-2140349646");
            _return.setNombre("Nombre1273651997");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see uytubeLogica.publicar.WebServices#seguirUsuario(java.lang.String arg0, java.lang.String arg1)*
     */
    public void seguirUsuario(java.lang.String arg0, java.lang.String arg1) {
        LOG.info("Executing operation seguirUsuario");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see uytubeLogica.publicar.WebServices#valorarVideo(int arg0, java.lang.String arg1, boolean arg2)*
     */
    public void valorarVideo(int arg0, java.lang.String arg1, boolean arg2) {
        LOG.info("Executing operation valorarVideo");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see uytubeLogica.publicar.WebServices#infoLDRdeUsuario(java.lang.String arg0, java.lang.String arg1, uytubeLogica.publicar.Privacidad arg2)*
     */
    public uytubeLogica.publicar.DtListaReproduccionArray infoLDRdeUsuario(java.lang.String arg0, java.lang.String arg1, Privacidad arg2) {
        LOG.info("Executing operation infoLDRdeUsuario");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        try {
            uytubeLogica.publicar.DtListaReproduccionArray _return = new uytubeLogica.publicar.DtListaReproduccionArray();
            java.util.List<uytubeLogica.publicar.DtListaReproduccion> _returnItem = new java.util.ArrayList<uytubeLogica.publicar.DtListaReproduccion>();
            uytubeLogica.publicar.DtListaReproduccion _returnItemVal1 = new uytubeLogica.publicar.DtListaReproduccion();
            java.util.List<uytubeLogica.publicar.DtCategoria> _returnItemVal1CategoriasLDR = new java.util.ArrayList<uytubeLogica.publicar.DtCategoria>();
            _returnItemVal1.getCategoriasLDR().addAll(_returnItemVal1CategoriasLDR);
            _returnItemVal1.setNombre("Nombre-1586096272");
            uytubeLogica.publicar.Privacidad _returnItemVal1Privado = uytubeLogica.publicar.Privacidad.PRIVADO;
            _returnItemVal1.setPrivado(_returnItemVal1Privado);
            _returnItemVal1.setPropietario("Propietario-612975778");
            uytubeLogica.publicar.TipoLista _returnItemVal1TipoL = uytubeLogica.publicar.TipoLista.PARTICULAR;
            _returnItemVal1.setTipoL(_returnItemVal1TipoL);
            _returnItemVal1.setUltimoVideo(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-10-28T15:58:54.709-03:00"));
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see uytubeLogica.publicar.WebServices#mostrarInfoCanal(java.lang.String arg0)*
     */
    public uytubeLogica.publicar.DtCanal mostrarInfoCanal(java.lang.String arg0) {
        LOG.info("Executing operation mostrarInfoCanal");
        System.out.println(arg0);
        try {
            uytubeLogica.publicar.DtCanal _return = new uytubeLogica.publicar.DtCanal();
            uytubeLogica.publicar.DtCategoria _returnCategoria = new uytubeLogica.publicar.DtCategoria();
            _returnCategoria.setNombre("Nombre-608644915");
            _return.setCategoria(_returnCategoria);
            _return.setDescripcion("Descripcion-545218073");
            _return.setNombre("Nombre-1540166898");
            uytubeLogica.publicar.Privacidad _returnPrivado = uytubeLogica.publicar.Privacidad.PUBLICO;
            _return.setPrivado(_returnPrivado);
            _return.setPropietario("Propietario-176381017");
            _return.setUltimoVideo(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-10-28T15:58:54.710-03:00"));
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see uytubeLogica.publicar.WebServices#agregarVideoLista(java.lang.String arg0, int arg1, java.lang.String arg2)*
     */
    public void agregarVideoLista(java.lang.String arg0, int arg1, java.lang.String arg2) {
        LOG.info("Executing operation agregarVideoLista");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see uytubeLogica.publicar.WebServices#verDetallesVideoExt(int arg0)*
     */
    public uytubeLogica.publicar.DtInfoVideo verDetallesVideoExt(int arg0) {
        LOG.info("Executing operation verDetallesVideoExt");
        System.out.println(arg0);
        try {
            uytubeLogica.publicar.DtInfoVideo _return = new uytubeLogica.publicar.DtInfoVideo();
            java.util.List<uytubeLogica.publicar.DtComentario> _returnComentarios = new java.util.ArrayList<uytubeLogica.publicar.DtComentario>();
            uytubeLogica.publicar.DtComentario _returnComentariosVal1 = new uytubeLogica.publicar.DtComentario();
            _returnComentariosVal1.setEsPadre(true);
            uytubeLogica.publicar.DtFecha _returnComentariosVal1Fecha = new uytubeLogica.publicar.DtFecha();
            _returnComentariosVal1Fecha.setFecha(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-10-28T15:58:54.712-03:00"));
            _returnComentariosVal1.setFecha(_returnComentariosVal1Fecha);
            byte[] _returnComentariosVal1FotoDuenio = new byte[] {};
            _returnComentariosVal1.setFotoDuenio(_returnComentariosVal1FotoDuenio);
            _returnComentariosVal1.setIdComentario(Integer.valueOf(-621768658));
            _returnComentariosVal1.setNickUsuario("NickUsuario1137055633");
            java.util.List<uytubeLogica.publicar.DtComentario> _returnComentariosVal1Respuestas = new java.util.ArrayList<uytubeLogica.publicar.DtComentario>();
            _returnComentariosVal1.getRespuestas().addAll(_returnComentariosVal1Respuestas);
            _returnComentariosVal1.setTexto("Texto-393160894");
            _returnComentarios.add(_returnComentariosVal1);
            _return.getComentarios().addAll(_returnComentarios);
            uytubeLogica.publicar.DtVideo _returnInfoVideo = new uytubeLogica.publicar.DtVideo();
            uytubeLogica.publicar.DtCategoria _returnInfoVideoCategoria = new uytubeLogica.publicar.DtCategoria();
            _returnInfoVideoCategoria.setNombre("Nombre1646473896");
            _returnInfoVideo.setCategoria(_returnInfoVideoCategoria);
            _returnInfoVideo.setDescripcion("Descripcion961937607");
            _returnInfoVideo.setDuracionSS(-1120047624);
            uytubeLogica.publicar.DtFecha _returnInfoVideoFechaPublicacion = new uytubeLogica.publicar.DtFecha();
            _returnInfoVideoFechaPublicacion.setFecha(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-10-28T15:58:54.713-03:00"));
            _returnInfoVideo.setFechaPublicacion(_returnInfoVideoFechaPublicacion);
            _returnInfoVideo.setNombre("Nombre1807785416");
            uytubeLogica.publicar.Privacidad _returnInfoVideoPrivacidad = uytubeLogica.publicar.Privacidad.PRIVADO;
            _returnInfoVideo.setPrivacidad(_returnInfoVideoPrivacidad);
            _returnInfoVideo.setPropietario("Propietario933363368");
            _returnInfoVideo.setUrl("Url833216365");
            _returnInfoVideo.setIDVideo(Integer.valueOf(1416163985));
            _return.setInfoVideo(_returnInfoVideo);
            java.util.List<uytubeLogica.publicar.DtUsuario> _returnUsuariosGusta = new java.util.ArrayList<uytubeLogica.publicar.DtUsuario>();
            uytubeLogica.publicar.DtUsuario _returnUsuariosGustaVal1 = new uytubeLogica.publicar.DtUsuario();
            _returnUsuariosGustaVal1.setApellido("Apellido1899956718");
            _returnUsuariosGustaVal1.setEmail("Email391285058");
            uytubeLogica.publicar.DtFecha _returnUsuariosGustaVal1FechaNacimiento = new uytubeLogica.publicar.DtFecha();
            _returnUsuariosGustaVal1FechaNacimiento.setFecha(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-10-28T15:58:54.713-03:00"));
            _returnUsuariosGustaVal1.setFechaNacimiento(_returnUsuariosGustaVal1FechaNacimiento);
            byte[] _returnUsuariosGustaVal1Foto = new byte[] {};
            _returnUsuariosGustaVal1.setFoto(_returnUsuariosGustaVal1Foto);
            _returnUsuariosGustaVal1.setNickname("Nickname1255446705");
            _returnUsuariosGustaVal1.setNombre("Nombre2123864229");
            _returnUsuariosGusta.add(_returnUsuariosGustaVal1);
            _return.getUsuariosGusta().addAll(_returnUsuariosGusta);
            java.util.List<uytubeLogica.publicar.DtUsuario> _returnUsuariosNoGusta = new java.util.ArrayList<uytubeLogica.publicar.DtUsuario>();
            uytubeLogica.publicar.DtUsuario _returnUsuariosNoGustaVal1 = new uytubeLogica.publicar.DtUsuario();
            _returnUsuariosNoGustaVal1.setApellido("Apellido-1132082130");
            _returnUsuariosNoGustaVal1.setEmail("Email-1890817580");
            uytubeLogica.publicar.DtFecha _returnUsuariosNoGustaVal1FechaNacimiento = new uytubeLogica.publicar.DtFecha();
            _returnUsuariosNoGustaVal1FechaNacimiento.setFecha(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-10-28T15:58:54.714-03:00"));
            _returnUsuariosNoGustaVal1.setFechaNacimiento(_returnUsuariosNoGustaVal1FechaNacimiento);
            byte[] _returnUsuariosNoGustaVal1Foto = new byte[] {};
            _returnUsuariosNoGustaVal1.setFoto(_returnUsuariosNoGustaVal1Foto);
            _returnUsuariosNoGustaVal1.setNickname("Nickname-1299618010");
            _returnUsuariosNoGustaVal1.setNombre("Nombre-767754882");
            _returnUsuariosNoGusta.add(_returnUsuariosNoGustaVal1);
            _return.getUsuariosNoGusta().addAll(_returnUsuariosNoGusta);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see uytubeLogica.publicar.WebServices#responderComentario(int arg0, int arg1, java.lang.String arg2, uytubeLogica.publicar.DtFecha arg3, java.lang.String arg4)*
     */
    public void responderComentario(int arg0, int arg1, java.lang.String arg2, DtFecha arg3, java.lang.String arg4) {
        LOG.info("Executing operation responderComentario");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        System.out.println(arg4);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    public boolean memberVideo(int arg0) {
        LOG.info("Executing operation memberVideo");
        System.out.println(arg0);
        try {
            boolean _return = true;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

	public void agregarVisita(int arg0, java.lang.String arg1) {
        LOG.info("Executing operation agregarVisita");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

	/* (non-Javadoc)
     * @see uytubeLogica.publicar.WebServices#listarVideosPorCategoria(java.lang.String arg0, uytubeLogica.publicar.Privacidad arg1, java.lang.String arg2)*
     */
    public uytubeLogica.publicar.DtVideoArray listarVideosPorCategoria(java.lang.String arg0, Privacidad arg1, java.lang.String arg2) {
        LOG.info("Executing operation listarVideosPorCategoria");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        try {
            uytubeLogica.publicar.DtVideoArray _return = new uytubeLogica.publicar.DtVideoArray();
            java.util.List<uytubeLogica.publicar.DtVideo> _returnItem = new java.util.ArrayList<uytubeLogica.publicar.DtVideo>();
            uytubeLogica.publicar.DtVideo _returnItemVal1 = new uytubeLogica.publicar.DtVideo();
            uytubeLogica.publicar.DtCategoria _returnItemVal1Categoria = new uytubeLogica.publicar.DtCategoria();
            _returnItemVal1Categoria.setNombre("Nombre171776911");
            _returnItemVal1.setCategoria(_returnItemVal1Categoria);
            _returnItemVal1.setDescripcion("Descripcion-1179853369");
            _returnItemVal1.setDuracionSS(-2145247907);
            uytubeLogica.publicar.DtFecha _returnItemVal1FechaPublicacion = new uytubeLogica.publicar.DtFecha();
            _returnItemVal1FechaPublicacion.setFecha(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-10-28T15:58:54.717-03:00"));
            _returnItemVal1.setFechaPublicacion(_returnItemVal1FechaPublicacion);
            _returnItemVal1.setNombre("Nombre877855761");
            uytubeLogica.publicar.Privacidad _returnItemVal1Privacidad = uytubeLogica.publicar.Privacidad.PRIVADO;
            _returnItemVal1.setPrivacidad(_returnItemVal1Privacidad);
            _returnItemVal1.setPropietario("Propietario1914766170");
            _returnItemVal1.setUrl("Url1317743853");
            _returnItemVal1.setIDVideo(Integer.valueOf(-1334379505));
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see uytubeLogica.publicar.WebServices#nuevoUsuario(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, java.lang.String arg3, java.lang.String arg4, uytubeLogica.publicar.DtFecha arg5, byte[] arg6, java.lang.String arg7, java.lang.String arg8, uytubeLogica.publicar.Privacidad arg9, java.lang.String arg10)*
     */
    public void nuevoUsuario(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, java.lang.String arg3, java.lang.String arg4, DtFecha arg5, byte[] arg6, java.lang.String arg7, java.lang.String arg8, Privacidad arg9, java.lang.String arg10) {
        LOG.info("Executing operation nuevoUsuario");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        System.out.println(arg4);
        System.out.println(arg5);
        System.out.println(arg6);
        System.out.println(arg7);
        System.out.println(arg8);
        System.out.println(arg9);
        System.out.println(arg10);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see uytubeLogica.publicar.WebServices#verificarLogin(java.lang.String arg0, java.lang.String arg1)*
     */
    public boolean verificarLogin(java.lang.String arg0, java.lang.String arg1) {
        LOG.info("Executing operation verificarLogin");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see uytubeLogica.publicar.WebServices#nuevaListaParticular(java.lang.String arg0, java.lang.String arg1, uytubeLogica.publicar.Privacidad arg2)*
     */
    public void nuevaListaParticular(java.lang.String arg0, java.lang.String arg1, Privacidad arg2) {
        LOG.info("Executing operation nuevaListaParticular");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see uytubeLogica.publicar.WebServices#nuevoComentario(int arg0, java.lang.String arg1, uytubeLogica.publicar.DtFecha arg2, java.lang.String arg3)*
     */
    public void nuevoComentario(int arg0, java.lang.String arg1, DtFecha arg2, java.lang.String arg3) {
        LOG.info("Executing operation nuevoComentario");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see uytubeLogica.publicar.WebServices#eliminarVideoLista(java.lang.String arg0, int arg1, java.lang.String arg2)*
     */
    public void eliminarVideoLista(java.lang.String arg0, int arg1, java.lang.String arg2) {
        LOG.info("Executing operation eliminarVideoLista");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see uytubeLogica.publicar.WebServices#listarVideoListaReproduccion(java.lang.String arg0, java.lang.String arg1)*
     */
    public uytubeLogica.publicar.DtVideoArray listarVideoListaReproduccion(java.lang.String arg0, java.lang.String arg1) {
        LOG.info("Executing operation listarVideoListaReproduccion");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            uytubeLogica.publicar.DtVideoArray _return = new uytubeLogica.publicar.DtVideoArray();
            java.util.List<uytubeLogica.publicar.DtVideo> _returnItem = new java.util.ArrayList<uytubeLogica.publicar.DtVideo>();
            uytubeLogica.publicar.DtVideo _returnItemVal1 = new uytubeLogica.publicar.DtVideo();
            uytubeLogica.publicar.DtCategoria _returnItemVal1Categoria = new uytubeLogica.publicar.DtCategoria();
            _returnItemVal1Categoria.setNombre("Nombre-214635391");
            _returnItemVal1.setCategoria(_returnItemVal1Categoria);
            _returnItemVal1.setDescripcion("Descripcion1679264134");
            _returnItemVal1.setDuracionSS(2056604007);
            uytubeLogica.publicar.DtFecha _returnItemVal1FechaPublicacion = new uytubeLogica.publicar.DtFecha();
            _returnItemVal1FechaPublicacion.setFecha(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-10-28T15:58:54.719-03:00"));
            _returnItemVal1.setFechaPublicacion(_returnItemVal1FechaPublicacion);
            _returnItemVal1.setNombre("Nombre52031196");
            uytubeLogica.publicar.Privacidad _returnItemVal1Privacidad = uytubeLogica.publicar.Privacidad.PUBLICO;
            _returnItemVal1.setPrivacidad(_returnItemVal1Privacidad);
            _returnItemVal1.setPropietario("Propietario1279732037");
            _returnItemVal1.setUrl("Url-450265072");
            _returnItemVal1.setIDVideo(Integer.valueOf(-251602568));
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see uytubeLogica.publicar.WebServices#getEstadoValoracion(int arg0, java.lang.String arg1)*
     */
    public java.lang.String getEstadoValoracion(int arg0, java.lang.String arg1) {
        LOG.info("Executing operation getEstadoValoracion");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.lang.String _return = "_return-370773758";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see uytubeLogica.publicar.WebServices#listarCategorias()*
     */
    public uytubeLogica.publicar.DtCategoriaArray listarCategorias() {
        LOG.info("Executing operation listarCategorias");
        try {
            uytubeLogica.publicar.DtCategoriaArray _return = new uytubeLogica.publicar.DtCategoriaArray();
            java.util.List<uytubeLogica.publicar.DtCategoria> _returnItem = new java.util.ArrayList<uytubeLogica.publicar.DtCategoria>();
            uytubeLogica.publicar.DtCategoria _returnItemVal1 = new uytubeLogica.publicar.DtCategoria();
            _returnItemVal1.setNombre("Nombre-771443127");
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    public uytubeLogica.publicar.DtVideoHistorialArray listarVideoHistorial(java.lang.String arg0) {
        LOG.info("Executing operation listarVideoHistorial");
        System.out.println(arg0);
        try {
            uytubeLogica.publicar.DtVideoHistorialArray _return = new uytubeLogica.publicar.DtVideoHistorialArray();
            java.util.List<uytubeLogica.publicar.DtVideoHistorial> _returnItem = new java.util.ArrayList<uytubeLogica.publicar.DtVideoHistorial>();
            uytubeLogica.publicar.DtVideoHistorial _returnItemVal1 = new uytubeLogica.publicar.DtVideoHistorial();
            uytubeLogica.publicar.DtFecha _returnItemVal1UltimaVisita = new uytubeLogica.publicar.DtFecha();
            _returnItemVal1UltimaVisita.setFecha(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-10-31T15:18:40.042-03:00"));
            _returnItemVal1.setUltimaVisita(_returnItemVal1UltimaVisita);
            uytubeLogica.publicar.DtVideo _returnItemVal1Video = new uytubeLogica.publicar.DtVideo();
            uytubeLogica.publicar.DtCategoria _returnItemVal1VideoCategoria = new uytubeLogica.publicar.DtCategoria();
            _returnItemVal1VideoCategoria.setNombre("Nombre-1706235754");
            _returnItemVal1Video.setCategoria(_returnItemVal1VideoCategoria);
            _returnItemVal1Video.setDescripcion("Descripcion-1628903202");
            _returnItemVal1Video.setDuracionSS(1466277558);
            uytubeLogica.publicar.DtFecha _returnItemVal1VideoFechaPublicacion = new uytubeLogica.publicar.DtFecha();
            _returnItemVal1VideoFechaPublicacion.setFecha(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-10-31T15:18:40.042-03:00"));
            _returnItemVal1Video.setFechaPublicacion(_returnItemVal1VideoFechaPublicacion);
            _returnItemVal1Video.setNombre("Nombre-960192962");
            uytubeLogica.publicar.Privacidad _returnItemVal1VideoPrivacidad = uytubeLogica.publicar.Privacidad.PUBLICO;
            _returnItemVal1Video.setPrivacidad(_returnItemVal1VideoPrivacidad);
            _returnItemVal1Video.setPropietario("Propietario1819933705");
            _returnItemVal1Video.setUrl("Url-1052327");
            _returnItemVal1Video.setIDVideo(Integer.valueOf(2083689435));
            _returnItemVal1.setVideo(_returnItemVal1Video);
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

	/* (non-Javadoc)
     * @see uytubeLogica.publicar.WebServices#memberListaReproduccionPropia(java.lang.String arg0, java.lang.String arg1)*
     */
    public boolean memberListaReproduccionPropia(java.lang.String arg0, java.lang.String arg1) {
        LOG.info("Executing operation memberListaReproduccionPropia");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see uytubeLogica.publicar.WebServices#listarComentarios(int arg0)*
     */
    public uytubeLogica.publicar.DtComentarioArray listarComentarios(int arg0) {
        LOG.info("Executing operation listarComentarios");
        System.out.println(arg0);
        try {
            uytubeLogica.publicar.DtComentarioArray _return = new uytubeLogica.publicar.DtComentarioArray();
            java.util.List<uytubeLogica.publicar.DtComentario> _returnItem = new java.util.ArrayList<uytubeLogica.publicar.DtComentario>();
            uytubeLogica.publicar.DtComentario _returnItemVal1 = new uytubeLogica.publicar.DtComentario();
            _returnItemVal1.setEsPadre(false);
            uytubeLogica.publicar.DtFecha _returnItemVal1Fecha = new uytubeLogica.publicar.DtFecha();
            _returnItemVal1Fecha.setFecha(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-10-28T15:58:54.720-03:00"));
            _returnItemVal1.setFecha(_returnItemVal1Fecha);
            byte[] _returnItemVal1FotoDuenio = new byte[] {};
            _returnItemVal1.setFotoDuenio(_returnItemVal1FotoDuenio);
            _returnItemVal1.setIdComentario(Integer.valueOf(1479820374));
            _returnItemVal1.setNickUsuario("NickUsuario-736868987");
            java.util.List<uytubeLogica.publicar.DtComentario> _returnItemVal1Respuestas = new java.util.ArrayList<uytubeLogica.publicar.DtComentario>();
            _returnItemVal1.getRespuestas().addAll(_returnItemVal1Respuestas);
            _returnItemVal1.setTexto("Texto-327017073");
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see uytubeLogica.publicar.WebServices#obtenerDtsVideosListaReproduccionUsuario(java.lang.String arg0, java.lang.String arg1)*
     */
    public uytubeLogica.publicar.DtVideoArray obtenerDtsVideosListaReproduccionUsuario(java.lang.String arg0, java.lang.String arg1) {
        LOG.info("Executing operation obtenerDtsVideosListaReproduccionUsuario");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            uytubeLogica.publicar.DtVideoArray _return = new uytubeLogica.publicar.DtVideoArray();
            java.util.List<uytubeLogica.publicar.DtVideo> _returnItem = new java.util.ArrayList<uytubeLogica.publicar.DtVideo>();
            uytubeLogica.publicar.DtVideo _returnItemVal1 = new uytubeLogica.publicar.DtVideo();
            uytubeLogica.publicar.DtCategoria _returnItemVal1Categoria = new uytubeLogica.publicar.DtCategoria();
            _returnItemVal1Categoria.setNombre("Nombre-288638675");
            _returnItemVal1.setCategoria(_returnItemVal1Categoria);
            _returnItemVal1.setDescripcion("Descripcion2087173308");
            _returnItemVal1.setDuracionSS(1857431255);
            uytubeLogica.publicar.DtFecha _returnItemVal1FechaPublicacion = new uytubeLogica.publicar.DtFecha();
            _returnItemVal1FechaPublicacion.setFecha(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-10-28T15:58:54.721-03:00"));
            _returnItemVal1.setFechaPublicacion(_returnItemVal1FechaPublicacion);
            _returnItemVal1.setNombre("Nombre-25230903");
            uytubeLogica.publicar.Privacidad _returnItemVal1Privacidad = uytubeLogica.publicar.Privacidad.PUBLICO;
            _returnItemVal1.setPrivacidad(_returnItemVal1Privacidad);
            _returnItemVal1.setPropietario("Propietario-1014670125");
            _returnItemVal1.setUrl("Url975053402");
            _returnItemVal1.setIDVideo(Integer.valueOf(-496636064));
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see uytubeLogica.publicar.WebServices#infoListaReproduccion(java.lang.String arg0, java.lang.String arg1)*
     */
    public uytubeLogica.publicar.DtListaReproduccion infoListaReproduccion(java.lang.String arg0, java.lang.String arg1) {
        LOG.info("Executing operation infoListaReproduccion");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            uytubeLogica.publicar.DtListaReproduccion _return = new uytubeLogica.publicar.DtListaReproduccion();
            java.util.List<uytubeLogica.publicar.DtCategoria> _returnCategoriasLDR = new java.util.ArrayList<uytubeLogica.publicar.DtCategoria>();
            uytubeLogica.publicar.DtCategoria _returnCategoriasLDRVal1 = new uytubeLogica.publicar.DtCategoria();
            _returnCategoriasLDRVal1.setNombre("Nombre1956200215");
            _returnCategoriasLDR.add(_returnCategoriasLDRVal1);
            _return.getCategoriasLDR().addAll(_returnCategoriasLDR);
            _return.setNombre("Nombre-1872162935");
            uytubeLogica.publicar.Privacidad _returnPrivado = uytubeLogica.publicar.Privacidad.PRIVADO;
            _return.setPrivado(_returnPrivado);
            _return.setPropietario("Propietario1055721370");
            uytubeLogica.publicar.TipoLista _returnTipoL = uytubeLogica.publicar.TipoLista.PARTICULAR;
            _return.setTipoL(_returnTipoL);
            _return.setUltimoVideo(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-10-28T15:58:54.722-03:00"));
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see uytubeLogica.publicar.WebServices#aniadirVideo(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, int arg3, uytubeLogica.publicar.DtFecha arg4, java.lang.String arg5, uytubeLogica.publicar.DtCategoria arg6, uytubeLogica.publicar.Privacidad arg7)*
     */
    public void aniadirVideo(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, int arg3, DtFecha arg4, java.lang.String arg5, DtCategoria arg6, Privacidad arg7) {
        LOG.info("Executing operation aniadirVideo");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        System.out.println(arg4);
        System.out.println(arg5);
        System.out.println(arg6);
        System.out.println(arg7);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see uytubeLogica.publicar.WebServices#listarUsuariosQueLeSigue(java.lang.String arg0)*
     */
    public net.java.dev.jaxb.array.StringArray listarUsuariosQueLeSigue(java.lang.String arg0) {
        LOG.info("Executing operation listarUsuariosQueLeSigue");
        System.out.println(arg0);
        try {
            net.java.dev.jaxb.array.StringArray _return = new net.java.dev.jaxb.array.StringArray();
            java.util.List<java.lang.String> _returnItem = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnItemVal1 = "_returnItemVal-1775978820";
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see uytubeLogica.publicar.WebServices#infoVideosCanal(java.lang.String arg0, java.lang.String arg1, uytubeLogica.publicar.Privacidad arg2)*
     */
    public uytubeLogica.publicar.DtVideoArray infoVideosCanal(java.lang.String arg0, java.lang.String arg1, Privacidad arg2) {
        LOG.info("Executing operation infoVideosCanal");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        try {
            uytubeLogica.publicar.DtVideoArray _return = new uytubeLogica.publicar.DtVideoArray();
            java.util.List<uytubeLogica.publicar.DtVideo> _returnItem = new java.util.ArrayList<uytubeLogica.publicar.DtVideo>();
            uytubeLogica.publicar.DtVideo _returnItemVal1 = new uytubeLogica.publicar.DtVideo();
            uytubeLogica.publicar.DtCategoria _returnItemVal1Categoria = new uytubeLogica.publicar.DtCategoria();
            _returnItemVal1Categoria.setNombre("Nombre1107111490");
            _returnItemVal1.setCategoria(_returnItemVal1Categoria);
            _returnItemVal1.setDescripcion("Descripcion-1402328167");
            _returnItemVal1.setDuracionSS(-593774130);
            uytubeLogica.publicar.DtFecha _returnItemVal1FechaPublicacion = new uytubeLogica.publicar.DtFecha();
            _returnItemVal1FechaPublicacion.setFecha(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-10-28T15:58:54.723-03:00"));
            _returnItemVal1.setFechaPublicacion(_returnItemVal1FechaPublicacion);
            _returnItemVal1.setNombre("Nombre-1352237021");
            uytubeLogica.publicar.Privacidad _returnItemVal1Privacidad = uytubeLogica.publicar.Privacidad.PRIVADO;
            _returnItemVal1.setPrivacidad(_returnItemVal1Privacidad);
            _returnItemVal1.setPropietario("Propietario849130977");
            _returnItemVal1.setUrl("Url-1495140531");
            _returnItemVal1.setIDVideo(Integer.valueOf(-1191893905));
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see uytubeLogica.publicar.WebServices#listarLDRdeUsuario(java.lang.String arg0)*
     */
    public net.java.dev.jaxb.array.StringArray listarLDRdeUsuario(java.lang.String arg0) {
        LOG.info("Executing operation listarLDRdeUsuario");
        System.out.println(arg0);
        try {
            net.java.dev.jaxb.array.StringArray _return = new net.java.dev.jaxb.array.StringArray();
            java.util.List<java.lang.String> _returnItem = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnItemVal1 = "_returnItemVal197856273";
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    public void bajaUsuario(java.lang.String arg0) {
        LOG.info("Executing operation bajaUsuario");
        System.out.println(arg0);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

	/* (non-Javadoc)
     * @see uytubeLogica.publicar.WebServices#infoAddVideo(int arg0)*
     */
    public uytubeLogica.publicar.DtVideo infoAddVideo(int arg0) {
        LOG.info("Executing operation infoAddVideo");
        System.out.println(arg0);
        try {
            uytubeLogica.publicar.DtVideo _return = new uytubeLogica.publicar.DtVideo();
            uytubeLogica.publicar.DtCategoria _returnCategoria = new uytubeLogica.publicar.DtCategoria();
            _returnCategoria.setNombre("Nombre-1113929705");
            _return.setCategoria(_returnCategoria);
            _return.setDescripcion("Descripcion764360289");
            _return.setDuracionSS(-980519763);
            uytubeLogica.publicar.DtFecha _returnFechaPublicacion = new uytubeLogica.publicar.DtFecha();
            _returnFechaPublicacion.setFecha(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-10-28T15:58:54.724-03:00"));
            _return.setFechaPublicacion(_returnFechaPublicacion);
            _return.setNombre("Nombre-957241626");
            uytubeLogica.publicar.Privacidad _returnPrivacidad = uytubeLogica.publicar.Privacidad.PRIVADO;
            _return.setPrivacidad(_returnPrivacidad);
            _return.setPropietario("Propietario793457349");
            _return.setUrl("Url-279520787");
            _return.setIDVideo(Integer.valueOf(-1611839120));
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see uytubeLogica.publicar.WebServices#cargarDatos()*
     */
    public void cargarDatos() {
        LOG.info("Executing operation cargarDatos");
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see uytubeLogica.publicar.WebServices#listarVideosPublicosPorNombre(java.lang.String arg0)*
     */
    public uytubeLogica.publicar.DtVideoArray listarVideosPublicosPorNombre(java.lang.String arg0) {
        LOG.info("Executing operation listarVideosPublicosPorNombre");
        System.out.println(arg0);
        try {
            uytubeLogica.publicar.DtVideoArray _return = new uytubeLogica.publicar.DtVideoArray();
            java.util.List<uytubeLogica.publicar.DtVideo> _returnItem = new java.util.ArrayList<uytubeLogica.publicar.DtVideo>();
            uytubeLogica.publicar.DtVideo _returnItemVal1 = new uytubeLogica.publicar.DtVideo();
            uytubeLogica.publicar.DtCategoria _returnItemVal1Categoria = new uytubeLogica.publicar.DtCategoria();
            _returnItemVal1Categoria.setNombre("Nombre-104780040");
            _returnItemVal1.setCategoria(_returnItemVal1Categoria);
            _returnItemVal1.setDescripcion("Descripcion-872457522");
            _returnItemVal1.setDuracionSS(-858871000);
            uytubeLogica.publicar.DtFecha _returnItemVal1FechaPublicacion = new uytubeLogica.publicar.DtFecha();
            _returnItemVal1FechaPublicacion.setFecha(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-10-28T15:58:54.729-03:00"));
            _returnItemVal1.setFechaPublicacion(_returnItemVal1FechaPublicacion);
            _returnItemVal1.setNombre("Nombre-1294533723");
            uytubeLogica.publicar.Privacidad _returnItemVal1Privacidad = uytubeLogica.publicar.Privacidad.PUBLICO;
            _returnItemVal1.setPrivacidad(_returnItemVal1Privacidad);
            _returnItemVal1.setPropietario("Propietario-1158211173");
            _returnItemVal1.setUrl("Url-13861538");
            _returnItemVal1.setIDVideo(Integer.valueOf(-1139776167));
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see uytubeLogica.publicar.WebServices#dejarUsuario(java.lang.String arg0, java.lang.String arg1)*
     */
    public void dejarUsuario(java.lang.String arg0, java.lang.String arg1) {
        LOG.info("Executing operation dejarUsuario");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
